import { assert } from "tsafe"

import { Url } from "@/utils/brandedTypes"
import { Option } from "@/utils/types/Option"

import { type Species, SpeciesId } from "./Species"

const allPlants: Species[] = [
  {
    id: SpeciesId("2cd4p9h.23w"),
    scientificName: "Succisa pratensis",
    family: "Caprifoliaceae",
    commonName: "Devil's-bit Scabious",
    alternativeCommonNames: ["Devil's-bit"],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.23w") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Succisa_pratensis") },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/devils-bit-scabious") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_scabious.html#Devil's-bit%20Scabious"),
      },
    ],
    idTips: ["Flower heads rounded with equal sized [[floret]]s", "All leaves [[entire]]", "[[Corolla]] 4-lobed"],
  },
  {
    id: SpeciesId("2cd4p9h.9b1"),
    scientificName: "Tanacetum vulgare",
    family: "Asteraceae",
    commonName: "Tansy",
    alternativeCommonNames: [],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.9b1") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Tanacetum_vulgare") },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/tansy") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_yellowbutton.html#Common%20Tansy"),
      },
    ],
    idTips: [
      "The plant has bright yellow, button-like flower heads arranged in flat-topped clusters.",
      "The flower heads lack [[ray florets]] and consist only of tightly packed [[disc florets]].",
      "The leaves are deeply divided into many narrow, toothed segments.",
    ],
  },
  {
    id: SpeciesId("2cd4p9h.yhw"),
    scientificName: "Tanacetum parthenium",
    family: "Asteraceae",
    commonName: "Feverfew",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yhw") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xyv"),
    scientificName: "Knautia arvensis",
    family: "Caprifoliaceae",
    commonName: "Field Scabious",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xyv") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.fpk"),
    scientificName: "Scabiosa columbaria",
    family: "Caprifoliaceae",
    commonName: "Small Scabious",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fpk") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.z9"),
    scientificName: "Hyacinthoides non-scripta",
    family: "Asparagaceae",
    commonName: "Bluebell",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.z9") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.bys"),
    scientificName: "Campanula rotundifolia",
    family: "Campanulaceae",
    commonName: "Harebell",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.bys") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xgb"),
    scientificName: "Cichorium intybus",
    family: "Asteraceae",
    commonName: "Chicory",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xgb") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vk1"),
    scientificName: "Jasione montana",
    family: "Campanulaceae",
    commonName: "Sheep's-bit",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vk1") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.cfz"),
    scientificName: "Ranunculus acris",
    family: "Ranunculaceae",
    commonName: "Meadow Buttercup",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cfz") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.1e3"),
    scientificName: "Lotus corniculatus",
    family: "Fabaceae",
    commonName: "Bird's-foot Trefoil",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1e3") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.94n"),
    scientificName: "Primula farinosa",
    family: "Primulaceae",
    commonName: "Bird's-eye Primrose",
    alternativeCommonNames: [],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.94n") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Primula_farinosa") },
    ],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.94t"),
    scientificName: "Primula veris",
    family: "Primulaceae",
    commonName: "Cowslip",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.94t") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8nb"),
    scientificName: "Geranium robertianum",
    family: "Geraniaceae",
    commonName: "Herb-Robert",
    alternativeCommonNames: ["Stinking Bob"],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8nb") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Geranium_robertianum") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_erodium.html#Common%20Herb-Robert"),
      },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/herb-robert") },
    ],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xxr"),
    scientificName: "Geranium lucidum",
    family: "Geraniaceae",
    commonName: "Shining Crane's-bill",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xxr") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xbs"),
    scientificName: "Bellis perennis",
    family: "Asteraceae",
    commonName: "Daisy",
    alternativeCommonNames: [],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xbs") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Bellis_perennis") },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/daisy") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_whitedaisies.html#Common%20Daisy"),
      },
    ],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.bwy"),
    scientificName: "Agrimonia eupatoria",
    family: "Rosaceae",
    commonName: "Agrimony",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.bwy") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.21r"),
    scientificName: "Smyrnium olusatrum",
    family: "Apiaceae",
    commonName: "Alexanders",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.21r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.x8s"),
    scientificName: "Alchemilla alpina",
    family: "Rosaceae",
    commonName: "Alpine Lady's-mantle",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.x8s") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yxr"),
    scientificName: "Fraxinus excelsior",
    family: "Oleaceae",
    commonName: "Ash",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yxr") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.fa2"),
    scientificName: "Fagus sylvatica",
    family: "Fagaceae",
    commonName: "Beech",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fa2") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.537"),
    scientificName: "Erica cinerea",
    family: "Ericaceae",
    commonName: "Bell Heather",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.537") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.w50"),
    scientificName: "Vaccinium myrtillus",
    family: "Ericaceae",
    commonName: "Bilberry",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w50") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.90z"),
    scientificName: "Narthecium ossifragum",
    family: "Nartheciaceae",
    commonName: "Bog Asphodel",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.90z") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.1g4"),
    scientificName: "Menyanthes trifoliata",
    family: "Menyanthaceae",
    commonName: "Bogbean",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1g4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.y9r"),
    scientificName: "Pteridium aquilinum",
    family: "Dennstaedtiaceae",
    commonName: "Bracken",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.y9r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vzf"),
    scientificName: "Rubus fruticosus",
    family: "Rosaceae",
    commonName: "Bramble",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vzf") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.cxx"),
    scientificName: "Sparganium erectum",
    family: "Typhaceae",
    commonName: "Branched Bur-reed",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cxx") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p9t"),
    scientificName: "Veronica beccabunga",
    family: "Plantaginaceae",
    commonName: "Brooklime",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p9t") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.m2y"),
    scientificName: "Cytisus scoparius",
    family: "Fabaceae",
    commonName: "Broom",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.m2y") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p05"),
    scientificName: "Plantago coronopus",
    family: "Plantaginaceae",
    commonName: "Buck's-horn Plantain",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p05") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xy"),
    scientificName: "Buddleja davidii",
    family: "Scrophulariaceae",
    commonName: "Butterfly-bush",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xy") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ez4"),
    scientificName: "Ajuga reptans",
    family: "Lamiaceae",
    commonName: "Bugle",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ez4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.5w9"),
    scientificName: "Ranunculus bulbosus",
    family: "Ranunculaceae",
    commonName: "Bulbous Buttercup",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5w9") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yzx"),
    scientificName: "Petasites hybridus",
    family: "Asteraceae",
    commonName: "Butterbur",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yzx") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ymq"),
    scientificName: "Galium aparine",
    family: "Rubiaceae",
    commonName: "Cleavers",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ymq") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.258"),
    scientificName: "Tussilago farfara",
    family: "Asteraceae",
    commonName: "Colt's-foot",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.258") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p02"),
    scientificName: "Pinguicula vulgaris",
    family: "Lentibulariaceae",
    commonName: "Common Butterwort",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p02") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.w2r"),
    scientificName: "Stellaria media",
    family: "Caryophyllaceae",
    commonName: "Common Chickweed",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w2r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yrz"),
    scientificName: "Melampyrum pratense",
    family: "Orobanchaceae",
    commonName: "Common Cow-wheat",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yrz") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.93r"),
    scientificName: "Polygala vulgaris",
    family: "Polygalaceae",
    commonName: "Common Milkwort",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.93r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.9c0"),
    scientificName: "Urtica dioica",
    family: "Urticaceae",
    commonName: "Common Nettle",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.9c0") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yzc"),
    scientificName: "Papaver rhoeas",
    family: "Papaveraceae",
    commonName: "Common Poppy",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yzc") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.4ms"),
    scientificName: "Alisma plantago-aquatica",
    family: "Alismataceae",
    commonName: "Water-plantain",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.4ms") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.v7e"),
    scientificName: "Anthriscus sylvestris",
    family: "Apiaceae",
    commonName: "Cow Parsley",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.v7e") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.26d"),
    scientificName: "Vaccinium vitis-idaea",
    family: "Ericaceae",
    commonName: "Cowberry",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.26d") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vt4"),
    scientificName: "Ranunculus repens",
    family: "Ranunculaceae",
    commonName: "Creeping Buttercup",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vt4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.c00"),
    scientificName: "Erica tetralix",
    family: "Ericaceae",
    commonName: "Cross-leaved Heath",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.c00") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.veg"),
    scientificName: "Empetrum nigrum",
    family: "Ericaceae",
    commonName: "Crowberry",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.veg") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ywh"),
    scientificName: "Digitalis purpurea",
    family: "Plantaginaceae",
    commonName: "Foxglove",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ywh") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.c87"),
    scientificName: "Lycopus europaeus",
    family: "Lamiaceae",
    commonName: "Gypsywort",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.c87") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p9b"),
    scientificName: "Ulex europaeus",
    family: "Fabaceae",
    commonName: "Gorse",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p9b") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vep"),
    scientificName: "Epilobium hirsutum",
    family: "Onagraceae",
    commonName: "Great Willowherb",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vep") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p08"),
    scientificName: "Plantago major",
    family: "Plantaginaceae",
    commonName: "Greater Plantain",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p08") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.6y7dfc"),
    scientificName: "Asplenium scolopendrium",
    family: "Aspleniaceae",
    commonName: "Hart's-tongue",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.6y7dfc") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.f6c"),
    scientificName: "Crataegus monogyna",
    family: "Rosaceae",
    commonName: "Hawthorn",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f6c") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yea"),
    scientificName: "Calluna vulgaris",
    family: "Ericaceae",
    commonName: "Heather",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yea") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.231"),
    scientificName: "Stachys sylvatica",
    family: "Lamiaceae",
    commonName: "Hedge Woundwort",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.231") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.brm"),
    scientificName: "Conium maculatum",
    family: "Apiaceae",
    commonName: "Hemlock",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.brm") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xwb"),
    scientificName: "Eupatorium cannabinum",
    family: "Asteraceae",
    commonName: "Hemp-agrimony",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xwb") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yp2"),
    scientificName: "Ilex aquifolium",
    family: "Aquifoliaceae",
    commonName: "Holly",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yp2") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.18x"),
    scientificName: "Impatiens glandulifera",
    family: "Balsaminaceae",
    commonName: "Himalayan Balsam",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.18x") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.95p1tn"),
    scientificName: "Hedera helix",
    family: "Araliaceae",
    commonName: "Common & Atlantic Ivy",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.95p1tn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.7mm4kb"),
    scientificName: "Reynoutria japonica",
    family: "Polygonaceae",
    commonName: "Japanese Knotweed",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.7mm4kb") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.6y9637"),
    scientificName: "Ficaria verna",
    family: "Ranunculaceae",
    commonName: "Lesser Celandine",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.6y9637") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.3ep"),
    scientificName: "Papaver dubium",
    family: "Papaveraceae",
    commonName: "Long-headed Poppy",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.3ep") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ycr"),
    scientificName: "Arum maculatum",
    family: "Araceae",
    commonName: "Lords-and-Ladies",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ycr") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.6y8hka"),
    scientificName: "Comarum palustre",
    family: "Rosaceae",
    commonName: "Marsh Cinquefoil",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.6y8hka") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ccc"),
    scientificName: "Pedicularis palustris",
    family: "Orobanchaceae",
    commonName: "Marsh Lousewort",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ccc") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8hn"),
    scientificName: "Cirsium palustre",
    family: "Asteraceae",
    commonName: "Marsh Thistle",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8hn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.m7w"),
    scientificName: "Viola palustris",
    family: "Violaceae",
    commonName: "Marsh Violet",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.m7w") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.f36"),
    scientificName: "Caltha palustris",
    family: "Ranunculaceae",
    commonName: "Marsh-marigold",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f36") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vvv"),
    scientificName: "Geranium pratense",
    family: "Geraniaceae",
    commonName: "Meadow Crane's-bill",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vvv") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.54r"),
    scientificName: "Filipendula ulmaria",
    family: "Rosaceae",
    commonName: "Meadowsweet",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.54r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.267"),
    scientificName: "Umbilicus rupestris",
    family: "Crassulaceae",
    commonName: "Navelwort",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.267") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.f5g"),
    scientificName: "Chrysosplenium oppositifolium",
    family: "Saxifragaceae",
    commonName: "Opposite-leaved Golden-saxifrage",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f5g") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.q4"),
    scientificName: "Leucanthemum vulgare",
    family: "Asteraceae",
    commonName: "Oxeye Daisy",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.q4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.5vd"),
    scientificName: "Primula vulgaris",
    family: "Primulaceae",
    commonName: "Primrose",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5vd") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vmn"),
    scientificName: "Lythrum salicaria",
    family: "Lythraceae",
    commonName: "Purple-loosestrife",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vmn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8a0"),
    scientificName: "Allium ursinum",
    family: "Amaryllidaceae",
    commonName: "Ramsons",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8a0") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vn4"),
    scientificName: "Silene dioica",
    family: "Caryophyllaceae",
    commonName: "Red Campion",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vn4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.cna"),
    scientificName: "Trifolium pratense",
    family: "Fabaceae",
    commonName: "Red Clover",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cna") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.c66"),
    scientificName: "Lamium purpureum",
    family: "Lamiaceae",
    commonName: "Red Dead-nettle",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.c66") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.9bp"),
    scientificName: "Typha latifolia",
    family: "Typhaceae",
    commonName: "Bulrush",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.9bp") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.1xk"),
    scientificName: "Plantago lanceolata",
    family: "Plantaginaceae",
    commonName: "Ribwort Plantain",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1xk") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.w2c"),
    scientificName: "Sorbus aucuparia",
    family: "Rosaceae",
    commonName: "Rowan",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w2c") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vek3vn"),
    scientificName: "Lysimachia arvensis",
    family: "Primulaceae",
    commonName: "Scarlet Pimpernel",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vek3vn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.fwn"),
    scientificName: "Pinus sylvestris",
    family: "Pinaceae",
    commonName: "Scots Pine",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fwn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p1p"),
    scientificName: "Prunella vulgaris",
    family: "Lamiaceae",
    commonName: "Selfheal",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p1p") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vzv"),
    scientificName: "Rumex acetosella",
    family: "Polygonaceae",
    commonName: "Sheep's Sorrel",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vzv") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.1n3"),
    scientificName: "Potentilla anserina",
    family: "Rosaceae",
    commonName: "Silverweed",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1n3") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.59a"),
    scientificName: "Iris foetidissima",
    family: "Iridaceae",
    commonName: "Stinking Iris",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.59a") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.fwh"),
    scientificName: "Phragmites australis",
    family: "Poaceae",
    commonName: "Common Reed",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fwh") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vdh"),
    scientificName: "Dipsacus fullonum",
    family: "Caprifoliaceae",
    commonName: "Wild Teasel",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vdh") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8b8"),
    scientificName: "Armeria maritima",
    family: "Plumbaginaceae",
    commonName: "Thrift",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8b8") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.5v7"),
    scientificName: "Potentilla erecta",
    family: "Rosaceae",
    commonName: "Tormentil",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5v7") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8hq"),
    scientificName: "Clematis vitalba",
    family: "Ranunculaceae",
    commonName: "Traveller's-joy",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8hq") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.5q2"),
    scientificName: "Vicia cracca",
    family: "Fabaceae",
    commonName: "Tufted Vetch",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5q2") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.w1g"),
    scientificName: "Scrophularia auriculata",
    family: "Scrophulariaceae",
    commonName: "Water Figwort",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w1g") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8rg"),
    scientificName: "Lamium album",
    family: "Lamiaceae",
    commonName: "White Dead-nettle",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8rg") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.k7f"),
    scientificName: "Daucus carota",
    family: "Apiaceae",
    commonName: "Carrots",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.k7f") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.gt"),
    scientificName: "Anemone nemorosa",
    family: "Ranunculaceae",
    commonName: "Wood Anemone",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.gt") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.cba"),
    scientificName: "Oxalis acetosella",
    family: "Oxalidaceae",
    commonName: "Wood-sorrel",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cba") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.f1t"),
    scientificName: "Galium odoratum",
    family: "Rubiaceae",
    commonName: "Woodruff",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f1t") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.88t"),
    scientificName: "Achillea millefolium",
    family: "Asteraceae",
    commonName: "Yarrow",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.88t") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vwt"),
    scientificName: "Iris pseudacorus",
    family: "Iridaceae",
    commonName: "Yellow Iris",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vwt") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.966"),
    scientificName: "Rhinanthus minor",
    family: "Orobanchaceae",
    commonName: "Yellow-rattle",
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.966") }],
    idTips: [],
  },
]

export const findSpecies = (id: SpeciesId): Option<Species> => allPlants.find((s) => s.id === id)

export const getSpecies = (id: SpeciesId): Species => {
  const species = findSpecies(id)
  assert(species, `Unknown species id: ${id}`)
  return species
}

export const getAllSpecies = (): Species[] => allPlants
