import { assert } from "tsafe"

import { Url } from "@/utils/brandedTypes"
import { Option } from "@/utils/types/Option"

import { CommonName, Family, ScientificName, type Species, SpeciesId } from "./Species"

export { filterSpecies } from "./Species"

const allPlants: Species[] = [
  {
    id: SpeciesId("2cd4p9h.23w"),
    scientificName: ScientificName("Succisa pratensis"),
    family: Family("Caprifoliaceae"),
    commonName: CommonName("Devil's-bit Scabious"),
    alternativeCommonNames: [CommonName("Devil's-bit")],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.23w") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Succisa_pratensis") },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/devils-bit-scabious") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_scabious.html#Devil's-bit%20Scabious"),
      },
    ],
    idTips: ["Flower heads rounded with equal sized [[floret]]s", "All leaves [[entire]]", "[[Corolla]] 4-lobed"],
  },
  {
    id: SpeciesId("2cd4p9h.9b1"),
    scientificName: ScientificName("Tanacetum vulgare"),
    family: Family("Asteraceae"),
    commonName: CommonName("Tansy"),
    alternativeCommonNames: [],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.9b1") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Tanacetum_vulgare") },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/tansy") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_yellowbutton.html#Common%20Tansy"),
      },
    ],
    idTips: [
      "The plant has bright yellow, button-like flower heads arranged in flat-topped clusters.",
      "The flower heads lack [[ray florets]] and consist only of tightly packed [[disc florets]].",
      "The leaves are deeply divided into many narrow, toothed segments.",
    ],
  },
  {
    id: SpeciesId("2cd4p9h.yhw"),
    scientificName: ScientificName("Tanacetum parthenium"),
    family: Family("Asteraceae"),
    commonName: CommonName("Feverfew"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yhw") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xyv"),
    scientificName: ScientificName("Knautia arvensis"),
    family: Family("Caprifoliaceae"),
    commonName: CommonName("Field Scabious"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xyv") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.fpk"),
    scientificName: ScientificName("Scabiosa columbaria"),
    family: Family("Caprifoliaceae"),
    commonName: CommonName("Small Scabious"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fpk") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.z9"),
    scientificName: ScientificName("Hyacinthoides non-scripta"),
    family: Family("Asparagaceae"),
    commonName: CommonName("Bluebell"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.z9") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.bys"),
    scientificName: ScientificName("Campanula rotundifolia"),
    family: Family("Campanulaceae"),
    commonName: CommonName("Harebell"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.bys") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xgb"),
    scientificName: ScientificName("Cichorium intybus"),
    family: Family("Asteraceae"),
    commonName: CommonName("Chicory"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xgb") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vk1"),
    scientificName: ScientificName("Jasione montana"),
    family: Family("Campanulaceae"),
    commonName: CommonName("Sheep's-bit"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vk1") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.cfz"),
    scientificName: ScientificName("Ranunculus acris"),
    family: Family("Ranunculaceae"),
    commonName: CommonName("Meadow Buttercup"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cfz") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.1e3"),
    scientificName: ScientificName("Lotus corniculatus"),
    family: Family("Fabaceae"),
    commonName: CommonName("Bird's-foot Trefoil"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1e3") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.94n"),
    scientificName: ScientificName("Primula farinosa"),
    family: Family("Primulaceae"),
    commonName: CommonName("Bird's-eye Primrose"),
    alternativeCommonNames: [],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.94n") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Primula_farinosa") },
    ],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.94t"),
    scientificName: ScientificName("Primula veris"),
    family: Family("Primulaceae"),
    commonName: CommonName("Cowslip"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.94t") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8nb"),
    scientificName: ScientificName("Geranium robertianum"),
    family: Family("Geraniaceae"),
    commonName: CommonName("Herb-Robert"),
    alternativeCommonNames: [CommonName("Stinking Bob")],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8nb") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Geranium_robertianum") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_erodium.html#Common%20Herb-Robert"),
      },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/herb-robert") },
    ],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xxr"),
    scientificName: ScientificName("Geranium lucidum"),
    family: Family("Geraniaceae"),
    commonName: CommonName("Shining Crane's-bill"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xxr") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xbs"),
    scientificName: ScientificName("Bellis perennis"),
    family: Family("Asteraceae"),
    commonName: CommonName("Daisy"),
    alternativeCommonNames: [],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xbs") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Bellis_perennis") },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/daisy") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_whitedaisies.html#Common%20Daisy"),
      },
    ],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.bwy"),
    scientificName: ScientificName("Agrimonia eupatoria"),
    family: Family("Rosaceae"),
    commonName: CommonName("Agrimony"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.bwy") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.21r"),
    scientificName: ScientificName("Smyrnium olusatrum"),
    family: Family("Apiaceae"),
    commonName: CommonName("Alexanders"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.21r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.x8s"),
    scientificName: ScientificName("Alchemilla alpina"),
    family: Family("Rosaceae"),
    commonName: CommonName("Alpine Lady's-mantle"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.x8s") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yxr"),
    scientificName: ScientificName("Fraxinus excelsior"),
    family: Family("Oleaceae"),
    commonName: CommonName("Ash"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yxr") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.fa2"),
    scientificName: ScientificName("Fagus sylvatica"),
    family: Family("Fagaceae"),
    commonName: CommonName("Beech"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fa2") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.537"),
    scientificName: ScientificName("Erica cinerea"),
    family: Family("Ericaceae"),
    commonName: CommonName("Bell Heather"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.537") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.w50"),
    scientificName: ScientificName("Vaccinium myrtillus"),
    family: Family("Ericaceae"),
    commonName: CommonName("Bilberry"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w50") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.90z"),
    scientificName: ScientificName("Narthecium ossifragum"),
    family: Family("Nartheciaceae"),
    commonName: CommonName("Bog Asphodel"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.90z") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.1g4"),
    scientificName: ScientificName("Menyanthes trifoliata"),
    family: Family("Menyanthaceae"),
    commonName: CommonName("Bogbean"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1g4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.y9r"),
    scientificName: ScientificName("Pteridium aquilinum"),
    family: Family("Dennstaedtiaceae"),
    commonName: CommonName("Bracken"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.y9r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vzf"),
    scientificName: ScientificName("Rubus fruticosus"),
    family: Family("Rosaceae"),
    commonName: CommonName("Bramble"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vzf") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.cxx"),
    scientificName: ScientificName("Sparganium erectum"),
    family: Family("Typhaceae"),
    commonName: CommonName("Branched Bur-reed"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cxx") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p9t"),
    scientificName: ScientificName("Veronica beccabunga"),
    family: Family("Plantaginaceae"),
    commonName: CommonName("Brooklime"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p9t") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.m2y"),
    scientificName: ScientificName("Cytisus scoparius"),
    family: Family("Fabaceae"),
    commonName: CommonName("Broom"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.m2y") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p05"),
    scientificName: ScientificName("Plantago coronopus"),
    family: Family("Plantaginaceae"),
    commonName: CommonName("Buck's-horn Plantain"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p05") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xy"),
    scientificName: ScientificName("Buddleja davidii"),
    family: Family("Scrophulariaceae"),
    commonName: CommonName("Butterfly-bush"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xy") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ez4"),
    scientificName: ScientificName("Ajuga reptans"),
    family: Family("Lamiaceae"),
    commonName: CommonName("Bugle"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ez4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.5w9"),
    scientificName: ScientificName("Ranunculus bulbosus"),
    family: Family("Ranunculaceae"),
    commonName: CommonName("Bulbous Buttercup"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5w9") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yzx"),
    scientificName: ScientificName("Petasites hybridus"),
    family: Family("Asteraceae"),
    commonName: CommonName("Butterbur"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yzx") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ymq"),
    scientificName: ScientificName("Galium aparine"),
    family: Family("Rubiaceae"),
    commonName: CommonName("Cleavers"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ymq") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.258"),
    scientificName: ScientificName("Tussilago farfara"),
    family: Family("Asteraceae"),
    commonName: CommonName("Colt's-foot"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.258") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p02"),
    scientificName: ScientificName("Pinguicula vulgaris"),
    family: Family("Lentibulariaceae"),
    commonName: CommonName("Common Butterwort"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p02") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.w2r"),
    scientificName: ScientificName("Stellaria media"),
    family: Family("Caryophyllaceae"),
    commonName: CommonName("Common Chickweed"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w2r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yrz"),
    scientificName: ScientificName("Melampyrum pratense"),
    family: Family("Orobanchaceae"),
    commonName: CommonName("Common Cow-wheat"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yrz") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.93r"),
    scientificName: ScientificName("Polygala vulgaris"),
    family: Family("Polygalaceae"),
    commonName: CommonName("Common Milkwort"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.93r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.9c0"),
    scientificName: ScientificName("Urtica dioica"),
    family: Family("Urticaceae"),
    commonName: CommonName("Common Nettle"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.9c0") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yzc"),
    scientificName: ScientificName("Papaver rhoeas"),
    family: Family("Papaveraceae"),
    commonName: CommonName("Common Poppy"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yzc") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.4ms"),
    scientificName: ScientificName("Alisma plantago-aquatica"),
    family: Family("Alismataceae"),
    commonName: CommonName("Water-plantain"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.4ms") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.v7e"),
    scientificName: ScientificName("Anthriscus sylvestris"),
    family: Family("Apiaceae"),
    commonName: CommonName("Cow Parsley"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.v7e") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.26d"),
    scientificName: ScientificName("Vaccinium vitis-idaea"),
    family: Family("Ericaceae"),
    commonName: CommonName("Cowberry"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.26d") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vt4"),
    scientificName: ScientificName("Ranunculus repens"),
    family: Family("Ranunculaceae"),
    commonName: CommonName("Creeping Buttercup"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vt4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.c00"),
    scientificName: ScientificName("Erica tetralix"),
    family: Family("Ericaceae"),
    commonName: CommonName("Cross-leaved Heath"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.c00") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.veg"),
    scientificName: ScientificName("Empetrum nigrum"),
    family: Family("Ericaceae"),
    commonName: CommonName("Crowberry"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.veg") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ywh"),
    scientificName: ScientificName("Digitalis purpurea"),
    family: Family("Plantaginaceae"),
    commonName: CommonName("Foxglove"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ywh") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.c87"),
    scientificName: ScientificName("Lycopus europaeus"),
    family: Family("Lamiaceae"),
    commonName: CommonName("Gypsywort"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.c87") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p9b"),
    scientificName: ScientificName("Ulex europaeus"),
    family: Family("Fabaceae"),
    commonName: CommonName("Gorse"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p9b") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vep"),
    scientificName: ScientificName("Epilobium hirsutum"),
    family: Family("Onagraceae"),
    commonName: CommonName("Great Willowherb"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vep") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p08"),
    scientificName: ScientificName("Plantago major"),
    family: Family("Plantaginaceae"),
    commonName: CommonName("Greater Plantain"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p08") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.6y7dfc"),
    scientificName: ScientificName("Asplenium scolopendrium"),
    family: Family("Aspleniaceae"),
    commonName: CommonName("Hart's-tongue"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.6y7dfc") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.f6c"),
    scientificName: ScientificName("Crataegus monogyna"),
    family: Family("Rosaceae"),
    commonName: CommonName("Hawthorn"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f6c") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yea"),
    scientificName: ScientificName("Calluna vulgaris"),
    family: Family("Ericaceae"),
    commonName: CommonName("Heather"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yea") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.231"),
    scientificName: ScientificName("Stachys sylvatica"),
    family: Family("Lamiaceae"),
    commonName: CommonName("Hedge Woundwort"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.231") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.brm"),
    scientificName: ScientificName("Conium maculatum"),
    family: Family("Apiaceae"),
    commonName: CommonName("Hemlock"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.brm") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.xwb"),
    scientificName: ScientificName("Eupatorium cannabinum"),
    family: Family("Asteraceae"),
    commonName: CommonName("Hemp-agrimony"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xwb") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.yp2"),
    scientificName: ScientificName("Ilex aquifolium"),
    family: Family("Aquifoliaceae"),
    commonName: CommonName("Holly"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yp2") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.18x"),
    scientificName: ScientificName("Impatiens glandulifera"),
    family: Family("Balsaminaceae"),
    commonName: CommonName("Himalayan Balsam"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.18x") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.95p1tn"),
    scientificName: ScientificName("Hedera helix"),
    family: Family("Araliaceae"),
    commonName: CommonName("Common & Atlantic Ivy"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.95p1tn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.7mm4kb"),
    scientificName: ScientificName("Reynoutria japonica"),
    family: Family("Polygonaceae"),
    commonName: CommonName("Japanese Knotweed"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.7mm4kb") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.6y9637"),
    scientificName: ScientificName("Ficaria verna"),
    family: Family("Ranunculaceae"),
    commonName: CommonName("Lesser Celandine"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.6y9637") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.3ep"),
    scientificName: ScientificName("Papaver dubium"),
    family: Family("Papaveraceae"),
    commonName: CommonName("Long-headed Poppy"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.3ep") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ycr"),
    scientificName: ScientificName("Arum maculatum"),
    family: Family("Araceae"),
    commonName: CommonName("Lords-and-Ladies"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ycr") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.6y8hka"),
    scientificName: ScientificName("Comarum palustre"),
    family: Family("Rosaceae"),
    commonName: CommonName("Marsh Cinquefoil"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.6y8hka") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.ccc"),
    scientificName: ScientificName("Pedicularis palustris"),
    family: Family("Orobanchaceae"),
    commonName: CommonName("Marsh Lousewort"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ccc") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8hn"),
    scientificName: ScientificName("Cirsium palustre"),
    family: Family("Asteraceae"),
    commonName: CommonName("Marsh Thistle"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8hn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.m7w"),
    scientificName: ScientificName("Viola palustris"),
    family: Family("Violaceae"),
    commonName: CommonName("Marsh Violet"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.m7w") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.f36"),
    scientificName: ScientificName("Caltha palustris"),
    family: Family("Ranunculaceae"),
    commonName: CommonName("Marsh-marigold"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f36") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vvv"),
    scientificName: ScientificName("Geranium pratense"),
    family: Family("Geraniaceae"),
    commonName: CommonName("Meadow Crane's-bill"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vvv") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.54r"),
    scientificName: ScientificName("Filipendula ulmaria"),
    family: Family("Rosaceae"),
    commonName: CommonName("Meadowsweet"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.54r") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.267"),
    scientificName: ScientificName("Umbilicus rupestris"),
    family: Family("Crassulaceae"),
    commonName: CommonName("Navelwort"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.267") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.f5g"),
    scientificName: ScientificName("Chrysosplenium oppositifolium"),
    family: Family("Saxifragaceae"),
    commonName: CommonName("Opposite-leaved Golden-saxifrage"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f5g") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.q4"),
    scientificName: ScientificName("Leucanthemum vulgare"),
    family: Family("Asteraceae"),
    commonName: CommonName("Oxeye Daisy"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.q4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.5vd"),
    scientificName: ScientificName("Primula vulgaris"),
    family: Family("Primulaceae"),
    commonName: CommonName("Primrose"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5vd") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vmn"),
    scientificName: ScientificName("Lythrum salicaria"),
    family: Family("Lythraceae"),
    commonName: CommonName("Purple-loosestrife"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vmn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8a0"),
    scientificName: ScientificName("Allium ursinum"),
    family: Family("Amaryllidaceae"),
    commonName: CommonName("Ramsons"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8a0") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vn4"),
    scientificName: ScientificName("Silene dioica"),
    family: Family("Caryophyllaceae"),
    commonName: CommonName("Red Campion"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vn4") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.cna"),
    scientificName: ScientificName("Trifolium pratense"),
    family: Family("Fabaceae"),
    commonName: CommonName("Red Clover"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cna") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.c66"),
    scientificName: ScientificName("Lamium purpureum"),
    family: Family("Lamiaceae"),
    commonName: CommonName("Red Dead-nettle"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.c66") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.9bp"),
    scientificName: ScientificName("Typha latifolia"),
    family: Family("Typhaceae"),
    commonName: CommonName("Bulrush"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.9bp") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.1xk"),
    scientificName: ScientificName("Plantago lanceolata"),
    family: Family("Plantaginaceae"),
    commonName: CommonName("Ribwort Plantain"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1xk") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.w2c"),
    scientificName: ScientificName("Sorbus aucuparia"),
    family: Family("Rosaceae"),
    commonName: CommonName("Rowan"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w2c") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vek3vn"),
    scientificName: ScientificName("Lysimachia arvensis"),
    family: Family("Primulaceae"),
    commonName: CommonName("Scarlet Pimpernel"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vek3vn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.fwn"),
    scientificName: ScientificName("Pinus sylvestris"),
    family: Family("Pinaceae"),
    commonName: CommonName("Scots Pine"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fwn") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.p1p"),
    scientificName: ScientificName("Prunella vulgaris"),
    family: Family("Lamiaceae"),
    commonName: CommonName("Selfheal"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p1p") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vzv"),
    scientificName: ScientificName("Rumex acetosella"),
    family: Family("Polygonaceae"),
    commonName: CommonName("Sheep's Sorrel"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vzv") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.1n3"),
    scientificName: ScientificName("Potentilla anserina"),
    family: Family("Rosaceae"),
    commonName: CommonName("Silverweed"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1n3") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.59a"),
    scientificName: ScientificName("Iris foetidissima"),
    family: Family("Iridaceae"),
    commonName: CommonName("Stinking Iris"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.59a") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.fwh"),
    scientificName: ScientificName("Phragmites australis"),
    family: Family("Poaceae"),
    commonName: CommonName("Common Reed"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fwh") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vdh"),
    scientificName: ScientificName("Dipsacus fullonum"),
    family: Family("Caprifoliaceae"),
    commonName: CommonName("Wild Teasel"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vdh") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8b8"),
    scientificName: ScientificName("Armeria maritima"),
    family: Family("Plumbaginaceae"),
    commonName: CommonName("Thrift"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8b8") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.5v7"),
    scientificName: ScientificName("Potentilla erecta"),
    family: Family("Rosaceae"),
    commonName: CommonName("Tormentil"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5v7") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8hq"),
    scientificName: ScientificName("Clematis vitalba"),
    family: Family("Ranunculaceae"),
    commonName: CommonName("Traveller's-joy"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8hq") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.5q2"),
    scientificName: ScientificName("Vicia cracca"),
    family: Family("Fabaceae"),
    commonName: CommonName("Tufted Vetch"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5q2") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.w1g"),
    scientificName: ScientificName("Scrophularia auriculata"),
    family: Family("Scrophulariaceae"),
    commonName: CommonName("Water Figwort"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w1g") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.8rg"),
    scientificName: ScientificName("Lamium album"),
    family: Family("Lamiaceae"),
    commonName: CommonName("White Dead-nettle"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8rg") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.k7f"),
    scientificName: ScientificName("Daucus carota"),
    family: Family("Apiaceae"),
    commonName: CommonName("Carrots"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.k7f") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.gt"),
    scientificName: ScientificName("Anemone nemorosa"),
    family: Family("Ranunculaceae"),
    commonName: CommonName("Wood Anemone"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.gt") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.cba"),
    scientificName: ScientificName("Oxalis acetosella"),
    family: Family("Oxalidaceae"),
    commonName: CommonName("Wood-sorrel"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cba") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.f1t"),
    scientificName: ScientificName("Galium odoratum"),
    family: Family("Rubiaceae"),
    commonName: CommonName("Woodruff"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f1t") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.88t"),
    scientificName: ScientificName("Achillea millefolium"),
    family: Family("Asteraceae"),
    commonName: CommonName("Yarrow"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.88t") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.vwt"),
    scientificName: ScientificName("Iris pseudacorus"),
    family: Family("Iridaceae"),
    commonName: CommonName("Yellow Iris"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vwt") }],
    idTips: [],
  },
  {
    id: SpeciesId("2cd4p9h.966"),
    scientificName: ScientificName("Rhinanthus minor"),
    family: Family("Orobanchaceae"),
    commonName: CommonName("Yellow-rattle"),
    alternativeCommonNames: [],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.966") }],
    idTips: [],
  },
]

export const findSpecies = (id: SpeciesId): Option<Species> => allPlants.find((s) => s.id === id)

export const getSpecies = (id: SpeciesId): Species => {
  const species = findSpecies(id)
  assert(species, `Unknown species id: ${id}`)
  return species
}

export const getAllSpecies = (): Species[] => allPlants
