packages:
  - apps/*
  - packages/*
  - infra

catalog:
  "@tanstack/react-query": 5.90.21
  "@types/node": 25.3.3
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  clsx: 2.1.1
  effect: 3.19.19
  eslint: 9.28.0
  jest-extended: 7.0.0
  lucide-react: 0.576.0
  mockttp: 4.2.1
  prettier: 3.8.1
  prettier-plugin-tailwindcss: 0.7.2
  react: 19.2.4
  react-dom: 19.2.4
  tailwind-merge: 3.5.0
  typescript: 5.9.3
  typescript-eslint: 8.56.1
  vitest: 4.0.18
  zod: 4.3.6
