name: wortle-infra
runtime:
  name: nodejs
  options:
    typescript: true
description: Infrastructure for wortle.app
packages:
  neon:
    source: terraform-provider
    version: 1.0.2
    parameters:
      - kislerdm/neon
