export const FAMILIES = [
  "Alismataceae",
  "Amaryllidaceae",
  "Apiaceae",
  "Araceae",
  "Araliaceae",
  "Asparagaceae",
  "Aspleniaceae",
  "Asteraceae",
  "Balsaminaceae",
  "Campanulaceae",
  "Caprifoliaceae",
  "Caryophyllaceae",
  "Crassulaceae",
  "Dennstaedtiaceae",
  "Ericaceae",
  "Fabaceae",
  "Fagaceae",
  "Geraniaceae",
  "Iridaceae",
  "Lamiaceae",
  "Lentibulariaceae",
  "Lythraceae",
  "Menyanthaceae",
  "Nartheciaceae",
  "Oleaceae",
  "Onagraceae",
  "Orobanchaceae",
  "Oxalidaceae",
  "Papaveraceae",
  "Pinaceae",
  "Plantaginaceae",
  "Plumbaginaceae",
  "Poaceae",
  "Polygalaceae",
  "Polygonaceae",
  "Primulaceae",
  "Ranunculaceae",
  "Rosaceae",
  "Rubiaceae",
  "Saxifragaceae",
  "Scrophulariaceae",
  "Typhaceae",
  "Urticaceae",
  "Violaceae",
] as const

export type Family = (typeof FAMILIES)[number]
